name: build
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Make gradle runner executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace --parallel --warning-mode=summary
      - name: Upload project libs
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs/
      - name: Upload subproject libs
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: ./*/build/libs/
